planeacion_admin_homepage:
    pattern:  /
    defaults: { _controller: PlaneacionAdminBundle:Default:index }
#-------Grupo----------------


planeacion_admin_crud_grupo_horario_expotar_hoja_html:
    pattern:  /admin/grupo/exportarHorarioHtml
    defaults: { _controller: PlaneacionAdminBundle:Grupo:exportarHorarioHtml }

#---------------------Descargas------------------------
planeacion_admin_crud_descargas:
    pattern:  /admin/descargas
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:main }

planeacion_admin_crud_descargas_listAjax:
    pattern:  /admin/descargas/list
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:listAjax}
planeacion_admin_crud_descargas_export_xls:
    pattern:  /gestionar/descargas/exportxls
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:exportXls}
planeacion_admin_crud_descargas_export_pdf:
    pattern:  /gestionar/descargas/exportPdf
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:exportPdf}
planeacion_admin_crud_descargas_edit:
    pattern:  /admin/descargas/edit
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:edit}

planeacion_admin_crud_descargas_new:
    pattern:  /admin/descargas/new
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:new}

planeacion_admin_crud_descargas_delete:
    pattern:  /admin/descargas/delete
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:delete }

planeacion_admin_crud_descargas_activar:
    pattern:  /admin/descargas/activar
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:activar }

planeacion_admin_crud_descargas_desactivar:
    pattern:  /admin/descargas/desactivar
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:desactivar }

planeacion_admin_crud_descargas_filtro_avanzado_view:
    pattern:  /admin/descargas/filtro
    defaults: { _controller: PlaneacionAdminBundle:DescargaAdministrativa:filtroAvanzado }

#---------------------Estudiante------------------------
planeacion_admin_crud_estudiante:
    pattern:  /admin/estudiante
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:main }

planeacion_admin_crud_estudiante_listAjax:
    pattern:  /admin/estudiante/list
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:listAjax}

planeacion_admin_crud_estudiante_export_pdf:
    pattern:  /gestionar/estudiante/exportPdf
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:exportPdf}
planeacion_admin_crud_estudiante_export_xls:
    pattern:  /gestionar/estudiante/exportxls
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:exportXls}
planeacion_admin_crud_estudiante_edit:
    pattern:  /admin/estudiante/edit
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:edit}
planeacion_admin_crud_estudiante_new:
    pattern:  /admin/estudiante/new
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:new}

planeacion_admin_crud_estudiante_delete:
    pattern:  /admin/estudiante/delete
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:delete }

planeacion_admin_crud_estudiante_activar:
    pattern:  /admin/estudiante/activar
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:activar }

planeacion_admin_crud_estudiante_desactivar:
    pattern:  /admin/estudiante/desactivar
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:desactivar }

planeacion_admin_crud_estudiante_filtro_avanzado_view:
    pattern:  /admin/estudiante/filtro
    defaults: { _controller: PlaneacionAdminBundle:Estudiante:filtroAvanzado }

#---------------------Materias------------------------
planeacion_admin_crud_materia:
    pattern:  /admin/materia
    defaults: { _controller: PlaneacionAdminBundle:Materia:main }

planeacion_admin_crud_materia_listAjax:
    pattern:  /admin/materia/list
    defaults: { _controller: PlaneacionAdminBundle:Materia:listAjax}

planeacion_admin_crud_materia_export_pdf:
    pattern:  /gestionar/materia/exportPdf
    defaults: { _controller: PlaneacionAdminBundle:Materia:exportPdf}
planeacion_admin_crud_materia_export_xls:
    pattern:  /gestionar/materia/exportxls
    defaults: { _controller: PlaneacionAdminBundle:Materia:exportXls}
planeacion_admin_crud_materia_edit:
    pattern:  /admin/materia/edit
    defaults: { _controller: PlaneacionAdminBundle:Materia:edit}
planeacion_admin_crud_materia_new:
    pattern:  /admin/materia/new
    defaults: { _controller: PlaneacionAdminBundle:Materia:new}

planeacion_admin_crud_materia_delete:
    pattern:  /admin/materia/delete
    defaults: { _controller: PlaneacionAdminBundle:Materia:delete }

planeacion_admin_crud_materia_activar:
    pattern:  /admin/materia/activar
    defaults: { _controller: PlaneacionAdminBundle:Materia:activar }

planeacion_admin_crud_materia_desactivar:
    pattern:  /admin/materia/desactivar
    defaults: { _controller: PlaneacionAdminBundle:Materia:desactivar }

planeacion_admin_crud_materia_filtro_avanzado_view:
    pattern:  /admin/materia/filtro
    defaults: { _controller: PlaneacionAdminBundle:Materia:filtroAvanzado }

#---------------------Categoria Profesoral------------------------
planeacion_admin_crud_category_professor:
    pattern:  /admin/category/profesor
    defaults: { _controller: PlaneacionAdminBundle:CategoryProfessor:main }

planeacion_admin_crud_category_professor_listAjax:
    pattern:  /admin/category/profesor/list
    defaults: { _controller: PlaneacionAdminBundle:CategoryProfessor:listAjax}


planeacion_admin_crud_category_professor_edit:
    pattern:  /admin/category/profesor/edit
    defaults: { _controller: PlaneacionAdminBundle:CategoryProfessor:edit}

planeacion_admin_crud_category_professor_new:
    pattern:  /admin/category/profesor/new
    defaults: { _controller: PlaneacionAdminBundle:CategoryProfessor:new}

planeacion_admin_crud_category_professor_delete:
    pattern:  /admin/category/profesor/delete
    defaults: { _controller: PlaneacionAdminBundle:CategoryProfessor:delete }

#---------------------Idioma------------------------
planeacion_admin_crud_idioma:
    pattern:  /admin/idioma
    defaults: { _controller: PlaneacionAdminBundle:Idioma:main }

planeacion_admin_crud_idioma_listAjax:
    pattern:  /admin/idioma/list
    defaults: { _controller: PlaneacionAdminBundle:Idioma:listAjax}


planeacion_admin_crud_idioma_edit:
    pattern:  /admin/idioma/edit
    defaults: { _controller: PlaneacionAdminBundle:Idioma:edit}

planeacion_admin_crud_idioma_new:
    pattern:  /admin/idioma/new
    defaults: { _controller: PlaneacionAdminBundle:Idioma:new}

planeacion_admin_crud_idioma_delete:
    pattern:  /admin/idioma/delete
    defaults: { _controller: PlaneacionAdminBundle:Idioma:delete }

#---------------------Profesor------------------------

planeacion_admin_crud_profesor_filtro_json_read_grupo:
    pattern:  /gestionar/profesor/json_read_grupo
    defaults: { _controller: PlaneacionAdminBundle:Profesor:jsonRead }

planeacion_admin_crud_profesor:
    pattern:  /gestionar/profesor
    defaults: { _controller: PlaneacionAdminBundle:Profesor:main }

planeacion_admin_crud_profesor_listAjax:
    pattern:  /gestionar/profesor/list
    defaults: { _controller: PlaneacionAdminBundle:Profesor:listAjax}

planeacion_admin_crud_profesor_edit_hoja_propia:
    pattern:  /planeacion/profesor/hoja
    defaults: { _controller: PlaneacionAdminBundle:ProfesorPropio:edit}

planeacion_admin_crud_profesor_edit:
    pattern:  /gestionar/profesor/edit
    defaults: { _controller: PlaneacionAdminBundle:Profesor:edit}

planeacion_admin_crud_profesor_new:
    pattern:  /gestionar/profesor/new
    defaults: { _controller: PlaneacionAdminBundle:Profesor:new}

planeacion_admin_crud_profesor_delete:
    pattern:  /gestionar/profesor/delete
    defaults: { _controller: PlaneacionAdminBundle:Profesor:delete }

planeacion_admin_crud_profesor_registro_materias:
    pattern:  /gestionar/profesor/registro_materias
    defaults: { _controller: PlaneacionAdminBundle:Profesor:registroMaterias}

planeacion_admin_crud_profesor_eliminar_registro_materias:
    pattern:  /gestionar/profesor/eliminar_registro_materias
    defaults: { _controller: PlaneacionAdminBundle:Profesor:eliminarMateriaHistorico}

planeacion_admin_crud_profesor_filtro_avanzado_view:
    pattern:  /gestionar/profesor/filtroAvanzadoView
    defaults: { _controller: PlaneacionAdminBundle:Profesor:filtroAvanzado}

planeacion_admin_crud_profesor_export:
    pattern:  /gestionar/profesor/export_generic
    defaults: { _controller: PlaneacionAdminBundle:Profesor:export}

planeacion_admin_crud_profesor_export_pdf:
    pattern:  /gestionar/profesor/exportPdf
    defaults: { _controller: PlaneacionAdminBundle:Profesor:exportPdf}
planeacion_admin_crud_profesor_export_xls:
    pattern:  /gestionar/profesor/exportxls
    defaults: { _controller: PlaneacionAdminBundle:Profesor:exportXls}
planeacion_admin_crud_profesor_export_correo:
    pattern:  /gestionar/profesor/exportCorreo
    defaults: { _controller: PlaneacionAdminBundle:Profesor:exportCorreo}
planeacion_admin_crud_profesor_expotar_hoja:
    pattern:  /gestionar/profesor/exportarHojaDatos
    defaults: { _controller: PlaneacionAdminBundle:Profesor:exportarHojasDeDatos }

#---------------------ProfesorHorarioss------------------------
planeacion_admin_crud_profesor_horario_expotar_hoja:
    pattern:  /gestionar/profesor_horario/exportarHorario
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:exportarHorario }

planeacion_admin_crud_profesor_horario_horas_periodo:
    pattern:  /gestionar/profesor_horario/horas_periodo
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:horasPeriodo}

planeacion_admin_crud_profesor_horario_json_read_grupo:
    pattern:  /gestionar/profesor_horario/json_read_grupo
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:jsonRead }

planeacion_admin_crud_profesor_horario:
    pattern:  /gestionar/profesor_horario
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:main }

planeacion_admin_crud_profesor_horario_listAjax:
    pattern:  /gestionar/profesor_horario/list
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:listAjax}


planeacion_admin_crud_profesor_horario_edit:
    pattern:  /gestionar/profesor_horario/edit
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:edit}

planeacion_admin_crud_profesor_horario_new:
    pattern:  /gestionar/profesor_horario/new
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:new}

planeacion_admin_crud_profesor_horario_delete:
    pattern:  /gestionar/profesor_horario/delete
    defaults: { _controller: PlaneacionAdminBundle:ProfesorHorarios:delete }

#---------------------PlanEstudio------------------------
planeacion_admin_crud_planEstudio:
    pattern:  /admin/planEstudio
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:main }

planeacion_admin_crud_planEstudio_listAjax:
    pattern:  /admin/planEstudio/list
    defaults: { _controller: PlaneacionAdminBundle:planEstudio:listAjax}


planeacion_admin_crud_planEstudio_edit:
    pattern:  /admin/planEstudio/edit
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:edit}

planeacion_admin_crud_planEstudio_new:
    pattern:  /admin/planEstudio/new
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:new}

planeacion_admin_crud_planEstudio_delete:
    pattern:  /admin/planEstudio/delete
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:delete }

planeacion_admin_crud_planEstudio_activar:
    pattern:  /admin/planEstudio/activar
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:activar }

planeacion_admin_crud_planEstudio_desactivar:
    pattern:  /admin/planEstudio/desactivar
    defaults: { _controller: PlaneacionAdminBundle:PlanEstudio:desactivar }

#---------------------GRUPO------------------------
planeacion_admin_crud_grupo:
    pattern:  /admin/grupo
    defaults: { _controller: PlaneacionAdminBundle:Grupo:main }

planeacion_admin_crud_grupo_listAjax:
    pattern:  /admin/grupo/list
    defaults: { _controller: PlaneacionAdminBundle:Grupo:listAjax}


planeacion_admin_crud_grupo_edit:
    pattern:  /admin/grupo/edit
    defaults: { _controller: PlaneacionAdminBundle:Grupo:edit}

planeacion_admin_crud_grupo_new:
    pattern:  /admin/grupo/new
    defaults: { _controller: PlaneacionAdminBundle:Grupo:new}

planeacion_admin_crud_grupo_delete:
    pattern:  /admin/grupo/delete
    defaults: { _controller: PlaneacionAdminBundle:Grupo:delete }

planeacion_admin_crud_grupo_export_pdf:
    pattern:  /admin/grupo/export_generic
    defaults: { _controller: PlaneacionAdminBundle:Grupo:exportPdf}
planeacion_admin_crud_grupo_horario_expotar_hoja:
    pattern:  /admin/grupo/exportarHorario
    defaults: { _controller: PlaneacionAdminBundle:Grupo:exportarHorario }
planeacion_admin_crud_grupo_export_xls:
    pattern:  /gestionar/grupo/exportxls
    defaults: { _controller: PlaneacionAdminBundle:Grupo:exportXls}
#---------------------HoraPeriodo------------------------
planeacion_admin_crud_hora_periodo:
    pattern:  /admin/hora_periodo
    defaults: { _controller: PlaneacionAdminBundle:HoraPeriodo:main }

planeacion_admin_crud_hora_periodo_listAjax:
    pattern:  /admin/hora_periodo/list
    defaults: { _controller: PlaneacionAdminBundle:HoraPeriodo:listAjax}


planeacion_admin_crud_hora_periodo_edit:
    pattern:  /admin/hora_periodo/edit
    defaults: { _controller: PlaneacionAdminBundle:HoraPeriodo:edit}

planeacion_admin_crud_hora_periodo_new:
    pattern:  /admin/hora_periodo/new
    defaults: { _controller: PlaneacionAdminBundle:HoraPeriodo:new}

planeacion_admin_crud_hora_periodo_delete:
    pattern:  /admin/hora_periodo/delete
    defaults: { _controller: PlaneacionAdminBundle:HoraPeriodo:delete }

#---------------------Aula------------------------
planeacion_admin_crud_aula:
    pattern:  /admin/aula
    defaults: { _controller: PlaneacionAdminBundle:Aula:main }

planeacion_admin_crud_aula_listAjax:
    pattern:  /admin/aula/list
    defaults: { _controller: PlaneacionAdminBundle:Aula:listAjax}


planeacion_admin_crud_aula_edit:
    pattern:  /admin/aula/edit
    defaults: { _controller: PlaneacionAdminBundle:Aula:edit}

planeacion_admin_crud_aula_new:
    pattern:  /admin/aula/new
    defaults: { _controller: PlaneacionAdminBundle:Aula:new}

planeacion_admin_crud_aula_delete:
    pattern:  /admin/aula/delete
    defaults: { _controller: PlaneacionAdminBundle:Aula:delete }

planeacion_admin_crud_aula_activar:
    pattern:  /admin/aula/activar
    defaults: { _controller: PlaneacionAdminBundle:Aula:activar }

planeacion_admin_crud_aula_desactivar:
    pattern:  /admin/aula/desactivar
    defaults: { _controller: PlaneacionAdminBundle:Aula:desactivar }

planeacion_admin_crud_aula_export:
    pattern:  /admin/aula/export_generic
    defaults: { _controller: PlaneacionAdminBundle:Aula:export}

planeacion_admin_crud_aula_export_pdf:
    pattern:  /admin/aula/exportPdf
    defaults: { _controller: PlaneacionAdminBundle:Aula:exportPdf}
planeacion_admin_crud_aula_export_xls:
    pattern:  /admin/aula/exportXls
    defaults: { _controller: PlaneacionAdminBundle:Aula:exportXls}
planeacion_admin_crud_aula_filtro_avanzado_view:
    pattern:  /admin/aula/filtroAvanzadoView
    defaults: { _controller: PlaneacionAdminBundle:Aula:filtroAvanzado}

#---------------------Periodo------------------------
planeacion_admin_crud_periodo:
    pattern:  /admin/periodo
    defaults: { _controller: PlaneacionAdminBundle:Periodo:main }

planeacion_admin_crud_periodo_listAjax:
    pattern:  /admin/periodo/list
    defaults: { _controller: PlaneacionAdminBundle:Periodo:listAjax}


planeacion_admin_crud_periodo_edit:
    pattern:  /admin/periodo/edit
    defaults: { _controller: PlaneacionAdminBundle:Periodo:edit}

planeacion_admin_crud_periodo_new:
    pattern:  /admin/periodo/new
    defaults: { _controller: PlaneacionAdminBundle:Periodo:new}

planeacion_admin_crud_periodo_delete:
    pattern:  /admin/periodo/delete
    defaults: { _controller: PlaneacionAdminBundle:Periodo:delete }

#---------------------Turno------------------------
planeacion_admin_crud_turno:
    pattern:  /admin/turno
    defaults: { _controller: PlaneacionAdminBundle:Turno:main }

planeacion_admin_crud_turno_listAjax:
    pattern:  /admin/turno/list
    defaults: { _controller: PlaneacionAdminBundle:Turno:listAjax}


planeacion_admin_crud_turno_edit:
    pattern:  /admin/turno/edit
    defaults: { _controller: PlaneacionAdminBundle:Turno:edit}

planeacion_admin_crud_turno_new:
    pattern:  /admin/turno/new
    defaults: { _controller: PlaneacionAdminBundle:Turno:new}

planeacion_admin_crud_turno_delete:
    pattern:  /admin/turno/delete
    defaults: { _controller: PlaneacionAdminBundle:Turno:delete }

planeacion_admin_crud_turno_activar:
    pattern:  /admin/turno/activar
    defaults: { _controller: PlaneacionAdminBundle:Turno:activar }

planeacion_admin_crud_turno_desactivar:
    pattern:  /admin/turno/desactivar
    defaults: { _controller: PlaneacionAdminBundle:Turno:desactivar }


#---------------------Hora------------------------
planeacion_admin_crud_hora:
    pattern:  /admin/hora
    defaults: { _controller: PlaneacionAdminBundle:Hora:main }

planeacion_admin_crud_hora_listAjax:
    pattern:  /admin/hora/list
    defaults: { _controller: PlaneacionAdminBundle:Hora:listAjax}


planeacion_admin_crud_hora_edit:
    pattern:  /admin/hora/edit
    defaults: { _controller: PlaneacionAdminBundle:Hora:edit}

planeacion_admin_crud_hora_new:
    pattern:  /admin/hora/new
    defaults: { _controller: PlaneacionAdminBundle:Hora:new}

planeacion_admin_crud_hora_delete:
    pattern:  /admin/hora/delete
    defaults: { _controller: PlaneacionAdminBundle:Hora:delete }

planeacion_admin_crud_hora_activar:
    pattern:  /admin/hora/activar
    defaults: { _controller: PlaneacionAdminBundle:Hora:activar }

planeacion_admin_crud_hora_desactivar:
    pattern:  /admin/hora/desactivar
    defaults: { _controller: PlaneacionAdminBundle:Hora:desactivar }

#---------------------Autoasignaci√≥n------------------------
planeacion_admin_crud_autoasignacion_aula:
    pattern:  /admin/autoasignacion
    defaults: { _controller: PlaneacionAdminBundle:AutoasignacionAula:main}
planeacion_admin_crud_autoasignacion_aula_listAjax:
    pattern:  /admin/autoasignacion/list
    defaults: { _controller: PlaneacionAdminBundle:AutoasignacionAula:listAjax}
planeacion_admin_crud_autoasignacion_aula_new:
    pattern:  /admin/autoasignacion/new
    defaults: { _controller: PlaneacionAdminBundle:AutoasignacionAula:new}
planeacion_admin_crud_autoasignacion_aula_delete:
    pattern:  /admin/autoasignacion/delete
    defaults: { _controller: PlaneacionAdminBundle:AutoasignacionAula:delete}
planeacion_admin_crud_autoasignacion_aula_edit:
    pattern:  /admin/autoasignacion/edit
    defaults: { _controller: PlaneacionAdminBundle:AutoasignacionAula:edit}